services:
  apache:
    image: php:8.2-apache
    container_name: apache
    ports:
      - "8800:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - mybridge
    command: >
      bash -c "
      docker-php-ext-install pdo pdo_mysql &&
      apache2-foreground
      "

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    restart: unless-stopped
    networks:
      - mybridge

  db:
    image: mariadb:11
    container_name: crypmerce_db
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: crypmerce_database
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secret123
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - mybridge

volumes:
  db_data:

networks:
  mybridge:
    driver: bridge
